import { describe, it, expect } from "vitest";
import {
  parseBackfillFlags,
  evaluateBackfillGuard,
  resolveRefreshOutputFormat,
} from "../backfill-recipe-images-utils";

describe("backfill-recipe-images-utils", () => {
  describe("evaluateBackfillGuard — the spend guard", () => {
    it("REFUSES a live run without Runware configured, naming the missing key", () => {
      const decision = evaluateBackfillGuard({
        dryRun: false,
        bumpOnly: false,
        runwareConfigured: false,
      });
      expect(decision.ok).toBe(false);
      if (decision.ok) return;
      expect(decision.reason).toContain("RUNWARE_API_KEY not set");
    });

    it("allows --dry-run and --bump-version-only without the key (no spend paths)", () => {
      expect(
        evaluateBackfillGuard({
          dryRun: true,
          bumpOnly: false,
          runwareConfigured: false,
        }).ok,
      ).toBe(true);
      expect(
        evaluateBackfillGuard({
          dryRun: false,
          bumpOnly: true,
          runwareConfigured: false,
        }).ok,
      ).toBe(true);
    });

    it("allows a live run when Runware is configured (non-vacuity control)", () => {
      expect(
        evaluateBackfillGuard({
          dryRun: false,
          bumpOnly: false,
          runwareConfigured: true,
        }).ok,
      ).toBe(true);
    });
  });

  describe("parseBackfillFlags", () => {
    it("defaults: no flags → live mode, no limit", () => {
      expect(parseBackfillFlags(["node", "script.ts"])).toEqual({
        dryRun: false,
        includeCanonical: false,
        bumpOnly: false,
        fillMissing: false,
        limit: Infinity,
      });
    });

    it("parses every boolean flag", () => {
      const flags = parseBackfillFlags([
        "node",
        "script.ts",
        "--dry-run",
        "--include-canonical",
        "--bump-version-only",
        "--fill-missing",
      ]);
      expect(flags.dryRun).toBe(true);
      expect(flags.includeCanonical).toBe(true);
      expect(flags.bumpOnly).toBe(true);
      expect(flags.fillMissing).toBe(true);
    });

    it("parses a numeric --limit", () => {
      expect(parseBackfillFlags(["node", "s", "--limit", "5"]).limit).toBe(5);
    });

    it("REJECTS a non-numeric --limit instead of silently disabling the cap", () => {
      // Regression: `--limit five` parsed to NaN, and every NaN comparison is
      // false — so the cap silently never engaged on a script that spends
      // real money per image. A typo'd limit must refuse, not run unbounded.
      expect(() =>
        parseBackfillFlags(["node", "s", "--limit", "five"]),
      ).toThrow(/--limit requires a positive integer/);
      expect(() => parseBackfillFlags(["node", "s", "--limit"])).toThrow(
        /--limit requires a positive integer/,
      );
      expect(() => parseBackfillFlags(["node", "s", "--limit", "0"])).toThrow(
        /--limit requires a positive integer/,
      );
    });
  });

  describe("resolveRefreshOutputFormat — the in-place-refresh outputFormat request", () => {
    // refreshInPlace() overwrites an EXISTING R2 key in place, so the
    // regenerated bytes must match whatever extension that key already
    // carries (the same ext refreshInPlace itself falls back to below).
    it("requests a real PNG for a preserved .png key", () => {
      expect(resolveRefreshOutputFormat("recipe-abc.png")).toBe("PNG");
    });

    it("keeps Runware's un-set default (JPEG) for a .jpg key", () => {
      // A literal "PNG" here would mislabel a .jpg key once this todo starts
      // writing .jpg keys for new images — the exact defect class this todo
      // fixes, just inverted.
      expect(resolveRefreshOutputFormat("recipe-abc.jpg")).toBeUndefined();
    });

    it("keeps the default for .jpeg", () => {
      expect(resolveRefreshOutputFormat("recipe-abc.jpeg")).toBeUndefined();
    });

    it("keeps the default for a legacy .webp key (unaddressed — out of scope)", () => {
      expect(resolveRefreshOutputFormat("recipe-abc.webp")).toBeUndefined();
    });

    it("falls back to PNG for an unrecognized extension, mirroring refreshInPlace's own save-ext fallback", () => {
      expect(resolveRefreshOutputFormat("recipe-abc")).toBe("PNG");
    });
  });
});
