#!/usr/bin/env tsx
import * as fs from "fs";
import * as path from "path";
import { PATH_TO_DOMAINS } from "./delegate-copilot-issue";

// Single source of truth: PATH_TO_DOMAINS is defined in
// delegate-copilot-issue.ts (typed, testable). This script consumes the
// rule descriptions and domains directly so the generated markdown table
// cannot drift from the script's detection logic. The synthetic
// "LLM-touching" row below isn't in PATH_TO_DOMAINS (it's a Set lookup,
// not a regex rule) so we render it as a manual row appended to the table.

const STACK_ORIENTATION = `OCRecipes is an Expo + React Native mobile app (Expo SDK 54, React 19, React Native 0.81) with an Express 5 + TypeScript backend. Database is PostgreSQL via Drizzle ORM. Authentication uses JWT bearer tokens (\`Authorization: Bearer ...\`, never cookies). Server state is managed with TanStack Query v5 on the client. AI features (coach chat, recipe generation, photo analysis, etc.) use OpenAI via a shared service layer.`;

const MANDATORY_WORKFLOW = `When the Issue body contains a \`## Project Rules\` section, every rule in it is binding. If a rule conflicts with an acceptance criterion, raise the conflict in a PR comment rather than silently violating the rule. If a rule isn't clear, open the corresponding \`docs/patterns/<domain>.md\` for full context.`;

const HARD_EXCLUSIONS = `## Hard Exclusions (never modify without a human-approved plan)

These domains require a human-authored implementation plan and are not eligible for Copilot delegation:

- JWT/auth (\`server/middleware/auth.ts\`, \`server/routes/auth.ts\`, \`server/lib/jwt-*\`)
- IAP receipt validation (\`server/services/receipt-validation.*\`)
- Secrets and credentials handling
- Health-data boundaries (\`server/services/healthkit*\`, \`server/storage/health.ts\`)
- Goal-safety behavior
- Schema and migrations (\`shared/schema.ts\`, \`migrations/**\`)
- Production data handling
- Broad architecture / cross-cutting overhauls

Output must be PR-based and human-reviewed. No auto-merge. No direct commits to \`main\`.`;

export function generateInstructions(): string {
  const tableHeader = "| Path pattern | Domains |\n| --- | --- |";
  const tableBody = PATH_TO_DOMAINS.map(
    (row) => `| ${row.description} | ${row.domains.join(", ")} |`,
  ).join("\n");
  // LLM-touching services row is added manually since it isn't a regex
  // rule in PATH_TO_DOMAINS (it's a Set lookup against basenames).
  const llmRow = `| \`server/services/<llm-touching>.ts\` (see LLM_TOUCHING_SERVICES) | architecture, ai-prompting |`;

  return `# Copilot Instructions for OCRecipes

${STACK_ORIENTATION}

## Mandatory workflow

${MANDATORY_WORKFLOW}

## Path → domain mapping

When editing a file, identify its domain(s) using the table below. The corresponding \`docs/rules/<domain>.md\` rules are binding for that file. Use \`docs/patterns/<domain>.md\` for full context if a rule isn't clear.

${tableHeader}
${tableBody}
${llmRow}

In addition, \`typescript\` rules apply to every \`.ts\` or \`.tsx\` file regardless of other domain matches.

${HARD_EXCLUSIONS}

---

*This file is generated by \`scripts/build-copilot-instructions.ts\`. Do not edit by hand — CI verifies the committed file matches what the script generates.*
`;
}

export function runBuildCli(argv: readonly string[]): number {
  const args = [...argv];
  const checkMode = args.includes("--check");
  if (checkMode) args.splice(args.indexOf("--check"), 1);

  const target = args[0];
  if (!target) {
    console.error("Usage: build-copilot-instructions [--check] <target-path>");
    return 2;
  }

  const generated = generateInstructions();

  if (checkMode) {
    if (!fs.existsSync(target)) {
      console.error(
        `[--check] ${target} does not exist. Run 'npm run build:copilot-instructions' to generate it.`,
      );
      return 1;
    }
    const current = fs.readFileSync(target, "utf8");
    if (current !== generated) {
      console.error(
        `[--check] ${target} is stale. Run 'npm run build:copilot-instructions' to update.`,
      );
      return 1;
    }
    console.log(`[--check] ${target} matches generated content.`);
    return 0;
  }

  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, generated);
  console.log(`Wrote ${target} (${generated.length} bytes)`);
  return 0;
}

// CLI entry point when invoked directly (not in tests).
if (
  require.main === module ||
  (typeof process !== "undefined" &&
    process.argv[1] &&
    process.argv[1].endsWith("build-copilot-instructions.ts"))
) {
  process.exit(runBuildCli(process.argv.slice(2)));
}
